services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Wacon\Filetransfer\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Wacon\Filetransfer\Service\FileUploadService:
    public: true

  Wacon\Filetransfer\Service\MailService:
    public: true
